'use client';

import type { PropsWithChildren } from 'react';
import '../styles/globals.css';

export default function RootLayout({ children }: PropsWithChildren): React.ReactElement {
  return (
    <html lang="ja">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.ico" />
      </head>
      <body>{children}</body>
    </html>
  );
}
